version: '3.7'

services:
   app:
      image: app
      build:
         context: .
         dockerfile: Dockerfile
         args:
            - PHP_VERSION=${PHP_VERSION:-7.2}
      container_name: php-chatcartel-V2
      volumes:
         - ./src:/var/www/html
      # extra_hosts:
      #    - "internal.host:host-gateway"
      networks:
         - chatcartel-lan

   nginx:
      image: nginx:alpine
      container_name: nginx-chatcartel-V2
      ports:
         - "${APP_PORT:-8882}:80"
      volumes:
         # - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:cached
         # - ./nginx/nginx.conf:/etc/nginx/nginx.conf:cached
         # - ./src:/var/www/html:cached
         - ./src:/var/www/html
         - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      restart: on-failure
      depends_on:
         - app
      networks:
         - chatcartel-lan

   supervisor:
      image: app
      networks:
         - chatcartel-lan
      depends_on:
         - app
         - nginx
      command: supervisord

   mysql:
      image: mysql:5.7
      container_name: mysql-chatcartel-V2
      restart: unless-stopped
      tty: true
      ports: 
         - 33062:3306
      volumes:
         - ./mysql:/var/lib/mysql
      environment:
         MYSQL_DATABASE: 'homestead'
         MYSQL_USER: 'homestead'
         MYSQL_PASSWORD: 'secret'
         MYSQL_ROOT_PASSWORD: 'secret.root'
         SERVICE_TAGS: dev
         SERVICE_NAME: mysql
      networks:
         - chatcartel-lan

networks:
   chatcartel-lan:
      driver: bridge
